data_path: data_and_artifacts/data_news/preprocessed/2023-10-01_2023-10-07/train
data_file: comp_data.parquet

# Define classes of the target, separating by the price_diff_percent  quantile
target_quantile: 0.05

# Max length of the text
max_len: 500
# Minimum frequency of the word to be added to the vocab
min_freq: 3

# Embedding dim
emb_dim: 500
# Hidden dim of LSTM
hidden_dim: 32
# Number of LSTM layers
n_layers: 1

epochs: 30
batch_size: 32
lr: 5e-4

model_path: data_and_artifacts/artifacts/models
model_file: comp_model.h5
vocab_path: data_and_artifacts/artifacts/vocabs
vocab_file: comp_vocab.pt
