initial_data_path: data_and_artifacts/data_news/raw
initial_file: full_data_2023-10-01_2023-10-07.parquet

final_data_path: data_and_artifacts/data_news/preprocessed

number_of_companies_in_one_news: 10
