services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  bot:
    build: .
    container_name: tg-bot
    restart: unless-stopped
    depends_on:
      - selenium
      - db
    networks:
      - internet
      - appnet
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
    restart: unless-stopped
    networks:
      - appnet
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'your_user'
      POSTGRES_PASSWORD: 'your_password'
      POSTGRES_DB: 'your_db'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge

volumes:
  pgdata:
  portainer_data:
