"""initial migration

 Revision ID: e5865326dea4
 Revises:
 Create Date: 2024-04-05 04:59:25.157460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5865326dea4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reviews", "score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("reviews", "feedback", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reviews", "feedback", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("reviews", "score", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
