name: Service-bot code check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.4 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"


      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy flake8
          cd Services && cd Service-bot
          pwd
          poetry install --no-root


      - name: Check typing with mypy
        run: |
          mypy \
          --disallow-untyped-defs \
          --ignore-missing-imports \
          --disable-error-code=name-defined \
          --disable-error-code=arg-type \
          --disable-error-code=index \
          --disable-error-code=operator \
          --disable-error-code=func-returns-value \
          --disable-error-code=import-untyped \
          --disable-error-code=call-arg \
          .

      - name: Check typing with flake8
        run: |
          flake8 \
          --ignore=W605,F401 \
          --max-line-length=88 \
          --max-complexity=10 \
          --exclude=.git,__pycache__,build,dist,.venv \
          .
